### ISSUE TITLE
Design Users, Interviews and Teams tables

### ISSUE THREAD

**Issue by starter69** [starter69/interview#2]
- Post fields of `users`, `interviews` and `teams` tables.
- If I approved those fields, and then make migrations for them.

**Comment by codegeek718** [comment]
**Users Table:**

| Field Name | Field Type |
|------------|------------|
| id         | int        |
| username   | varchar    |
| password   | varchar    |
| team_id    | int        |
| role    | enum    |

**Teams Table:**

| Field Name | Field Type |
|------------|------------|
| id         | int        |
| team_name  | varchar    |

**Interviews Table:**

| Field Name | Field Type |
|------------|------------|
| id         | int        |
| user_id    | int        |
| name       | varchar    |
| date       | date       |
| duration   | int        |
| path       | varchar    |
